# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'familyclock' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for familyclock

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'familyclockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'familyclockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
